services:
  petclinic:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
    volumes:
      - .:/app
    networks:
      - petclinic
    depends_on:
      - mysqlserver
    
  mysqlserver:
    image: hlebsur/mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - petclinic
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=information_schema

volumes:
  mysql_data:
  mysql_config:

networks:
  petclinic:
    driver: bridge
